/*
Service API

API for managing services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapregistrysdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRouteRequest{}

// UpdateRouteRequest struct for UpdateRouteRequest
type UpdateRouteRequest struct {
	// 路由名称
	Name string `json:"name"`
	// 此路由关联的网关标识
	GatewayId *string `json:"gateway_id,omitempty"`
	// 支持的协议列表
	Protocols []string `json:"protocols,omitempty"`
	// 匹配的HTTP方法列表
	Methods []string `json:"methods,omitempty"`
	// 匹配的Host列表
	Hosts []string `json:"hosts,omitempty"`
	// 匹配的路径
	Paths []string `json:"paths,omitempty"`
	// 匹配的请求头
	Headers []string `json:"headers,omitempty"`
	// 协议不匹配时的重定向状态码
	HttpsRedirectStatusCode *int32 `json:"https_redirect_status_code,omitempty"`
	// 正则匹配优先级
	RegexPriority *int32 `json:"regex_priority,omitempty"`
	// 是否移除路径前缀
	StripPath *bool `json:"strip_path,omitempty"`
	// 是否保留原始请求的Host头
	PreserveHost *bool `json:"preserve_host,omitempty"`
	// 是否缓冲请求体数据
	RequestBuffering *bool `json:"request_buffering,omitempty"`
	// 是否缓冲响应体数据
	ResponseBuffering *bool `json:"response_buffering,omitempty"`
	// 支持的SNI列表
	Snis []string `json:"snis,omitempty"`
	// 允许的源IP列表
	Sources []string `json:"sources,omitempty"`
	// 目标服务地址列表
	Destinations []string `json:"destinations,omitempty"`
	// 路由标签
	Tags []string `json:"tags,omitempty"`
	// Agent/Tool通信协议
	AgentProtocol *string `json:"agent_protocol,omitempty"`
	// 关联的服务名
	Service *string `json:"service,omitempty"`
}

type _UpdateRouteRequest UpdateRouteRequest

// NewUpdateRouteRequest instantiates a new UpdateRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRouteRequest(name string) *UpdateRouteRequest {
	this := UpdateRouteRequest{}
	this.Name = name
	return &this
}

// NewUpdateRouteRequestWithDefaults instantiates a new UpdateRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRouteRequestWithDefaults() *UpdateRouteRequest {
	this := UpdateRouteRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateRouteRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateRouteRequest) SetName(v string) {
	o.Name = v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *UpdateRouteRequest) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetProtocols returns the Protocols field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetProtocols() []string {
	if o == nil || IsNil(o.Protocols) {
		var ret []string
		return ret
	}
	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetProtocolsOk() ([]string, bool) {
	if o == nil || IsNil(o.Protocols) {
		return nil, false
	}
	return o.Protocols, true
}

// HasProtocols returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasProtocols() bool {
	if o != nil && !IsNil(o.Protocols) {
		return true
	}

	return false
}

// SetProtocols gets a reference to the given []string and assigns it to the Protocols field.
func (o *UpdateRouteRequest) SetProtocols(v []string) {
	o.Protocols = v
}

// GetMethods returns the Methods field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetMethods() []string {
	if o == nil || IsNil(o.Methods) {
		var ret []string
		return ret
	}
	return o.Methods
}

// GetMethodsOk returns a tuple with the Methods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.Methods) {
		return nil, false
	}
	return o.Methods, true
}

// HasMethods returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasMethods() bool {
	if o != nil && !IsNil(o.Methods) {
		return true
	}

	return false
}

// SetMethods gets a reference to the given []string and assigns it to the Methods field.
func (o *UpdateRouteRequest) SetMethods(v []string) {
	o.Methods = v
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetHosts() []string {
	if o == nil || IsNil(o.Hosts) {
		var ret []string
		return ret
	}
	return o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *UpdateRouteRequest) SetHosts(v []string) {
	o.Hosts = v
}

// GetPaths returns the Paths field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetPaths() []string {
	if o == nil || IsNil(o.Paths) {
		var ret []string
		return ret
	}
	return o.Paths
}

// GetPathsOk returns a tuple with the Paths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.Paths) {
		return nil, false
	}
	return o.Paths, true
}

// HasPaths returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasPaths() bool {
	if o != nil && !IsNil(o.Paths) {
		return true
	}

	return false
}

// SetPaths gets a reference to the given []string and assigns it to the Paths field.
func (o *UpdateRouteRequest) SetPaths(v []string) {
	o.Paths = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetHeaders() []string {
	if o == nil || IsNil(o.Headers) {
		var ret []string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []string and assigns it to the Headers field.
func (o *UpdateRouteRequest) SetHeaders(v []string) {
	o.Headers = v
}

// GetHttpsRedirectStatusCode returns the HttpsRedirectStatusCode field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetHttpsRedirectStatusCode() int32 {
	if o == nil || IsNil(o.HttpsRedirectStatusCode) {
		var ret int32
		return ret
	}
	return *o.HttpsRedirectStatusCode
}

// GetHttpsRedirectStatusCodeOk returns a tuple with the HttpsRedirectStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetHttpsRedirectStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpsRedirectStatusCode) {
		return nil, false
	}
	return o.HttpsRedirectStatusCode, true
}

// HasHttpsRedirectStatusCode returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasHttpsRedirectStatusCode() bool {
	if o != nil && !IsNil(o.HttpsRedirectStatusCode) {
		return true
	}

	return false
}

// SetHttpsRedirectStatusCode gets a reference to the given int32 and assigns it to the HttpsRedirectStatusCode field.
func (o *UpdateRouteRequest) SetHttpsRedirectStatusCode(v int32) {
	o.HttpsRedirectStatusCode = &v
}

// GetRegexPriority returns the RegexPriority field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetRegexPriority() int32 {
	if o == nil || IsNil(o.RegexPriority) {
		var ret int32
		return ret
	}
	return *o.RegexPriority
}

// GetRegexPriorityOk returns a tuple with the RegexPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetRegexPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.RegexPriority) {
		return nil, false
	}
	return o.RegexPriority, true
}

// HasRegexPriority returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasRegexPriority() bool {
	if o != nil && !IsNil(o.RegexPriority) {
		return true
	}

	return false
}

// SetRegexPriority gets a reference to the given int32 and assigns it to the RegexPriority field.
func (o *UpdateRouteRequest) SetRegexPriority(v int32) {
	o.RegexPriority = &v
}

// GetStripPath returns the StripPath field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetStripPath() bool {
	if o == nil || IsNil(o.StripPath) {
		var ret bool
		return ret
	}
	return *o.StripPath
}

// GetStripPathOk returns a tuple with the StripPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetStripPathOk() (*bool, bool) {
	if o == nil || IsNil(o.StripPath) {
		return nil, false
	}
	return o.StripPath, true
}

// HasStripPath returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasStripPath() bool {
	if o != nil && !IsNil(o.StripPath) {
		return true
	}

	return false
}

// SetStripPath gets a reference to the given bool and assigns it to the StripPath field.
func (o *UpdateRouteRequest) SetStripPath(v bool) {
	o.StripPath = &v
}

// GetPreserveHost returns the PreserveHost field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetPreserveHost() bool {
	if o == nil || IsNil(o.PreserveHost) {
		var ret bool
		return ret
	}
	return *o.PreserveHost
}

// GetPreserveHostOk returns a tuple with the PreserveHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetPreserveHostOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveHost) {
		return nil, false
	}
	return o.PreserveHost, true
}

// HasPreserveHost returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasPreserveHost() bool {
	if o != nil && !IsNil(o.PreserveHost) {
		return true
	}

	return false
}

// SetPreserveHost gets a reference to the given bool and assigns it to the PreserveHost field.
func (o *UpdateRouteRequest) SetPreserveHost(v bool) {
	o.PreserveHost = &v
}

// GetRequestBuffering returns the RequestBuffering field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetRequestBuffering() bool {
	if o == nil || IsNil(o.RequestBuffering) {
		var ret bool
		return ret
	}
	return *o.RequestBuffering
}

// GetRequestBufferingOk returns a tuple with the RequestBuffering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetRequestBufferingOk() (*bool, bool) {
	if o == nil || IsNil(o.RequestBuffering) {
		return nil, false
	}
	return o.RequestBuffering, true
}

// HasRequestBuffering returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasRequestBuffering() bool {
	if o != nil && !IsNil(o.RequestBuffering) {
		return true
	}

	return false
}

// SetRequestBuffering gets a reference to the given bool and assigns it to the RequestBuffering field.
func (o *UpdateRouteRequest) SetRequestBuffering(v bool) {
	o.RequestBuffering = &v
}

// GetResponseBuffering returns the ResponseBuffering field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetResponseBuffering() bool {
	if o == nil || IsNil(o.ResponseBuffering) {
		var ret bool
		return ret
	}
	return *o.ResponseBuffering
}

// GetResponseBufferingOk returns a tuple with the ResponseBuffering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetResponseBufferingOk() (*bool, bool) {
	if o == nil || IsNil(o.ResponseBuffering) {
		return nil, false
	}
	return o.ResponseBuffering, true
}

// HasResponseBuffering returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasResponseBuffering() bool {
	if o != nil && !IsNil(o.ResponseBuffering) {
		return true
	}

	return false
}

// SetResponseBuffering gets a reference to the given bool and assigns it to the ResponseBuffering field.
func (o *UpdateRouteRequest) SetResponseBuffering(v bool) {
	o.ResponseBuffering = &v
}

// GetSnis returns the Snis field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetSnis() []string {
	if o == nil || IsNil(o.Snis) {
		var ret []string
		return ret
	}
	return o.Snis
}

// GetSnisOk returns a tuple with the Snis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetSnisOk() ([]string, bool) {
	if o == nil || IsNil(o.Snis) {
		return nil, false
	}
	return o.Snis, true
}

// HasSnis returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasSnis() bool {
	if o != nil && !IsNil(o.Snis) {
		return true
	}

	return false
}

// SetSnis gets a reference to the given []string and assigns it to the Snis field.
func (o *UpdateRouteRequest) SetSnis(v []string) {
	o.Snis = v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *UpdateRouteRequest) SetSources(v []string) {
	o.Sources = v
}

// GetDestinations returns the Destinations field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetDestinations() []string {
	if o == nil || IsNil(o.Destinations) {
		var ret []string
		return ret
	}
	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetDestinationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Destinations) {
		return nil, false
	}
	return o.Destinations, true
}

// HasDestinations returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasDestinations() bool {
	if o != nil && !IsNil(o.Destinations) {
		return true
	}

	return false
}

// SetDestinations gets a reference to the given []string and assigns it to the Destinations field.
func (o *UpdateRouteRequest) SetDestinations(v []string) {
	o.Destinations = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *UpdateRouteRequest) SetTags(v []string) {
	o.Tags = v
}

// GetAgentProtocol returns the AgentProtocol field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetAgentProtocol() string {
	if o == nil || IsNil(o.AgentProtocol) {
		var ret string
		return ret
	}
	return *o.AgentProtocol
}

// GetAgentProtocolOk returns a tuple with the AgentProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetAgentProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.AgentProtocol) {
		return nil, false
	}
	return o.AgentProtocol, true
}

// HasAgentProtocol returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasAgentProtocol() bool {
	if o != nil && !IsNil(o.AgentProtocol) {
		return true
	}

	return false
}

// SetAgentProtocol gets a reference to the given string and assigns it to the AgentProtocol field.
func (o *UpdateRouteRequest) SetAgentProtocol(v string) {
	o.AgentProtocol = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *UpdateRouteRequest) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRouteRequest) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *UpdateRouteRequest) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *UpdateRouteRequest) SetService(v string) {
	o.Service = &v
}

func (o UpdateRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.GatewayId) {
		toSerialize["gateway_id"] = o.GatewayId
	}
	if !IsNil(o.Protocols) {
		toSerialize["protocols"] = o.Protocols
	}
	if !IsNil(o.Methods) {
		toSerialize["methods"] = o.Methods
	}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.Paths) {
		toSerialize["paths"] = o.Paths
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.HttpsRedirectStatusCode) {
		toSerialize["https_redirect_status_code"] = o.HttpsRedirectStatusCode
	}
	if !IsNil(o.RegexPriority) {
		toSerialize["regex_priority"] = o.RegexPriority
	}
	if !IsNil(o.StripPath) {
		toSerialize["strip_path"] = o.StripPath
	}
	if !IsNil(o.PreserveHost) {
		toSerialize["preserve_host"] = o.PreserveHost
	}
	if !IsNil(o.RequestBuffering) {
		toSerialize["request_buffering"] = o.RequestBuffering
	}
	if !IsNil(o.ResponseBuffering) {
		toSerialize["response_buffering"] = o.ResponseBuffering
	}
	if !IsNil(o.Snis) {
		toSerialize["snis"] = o.Snis
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Destinations) {
		toSerialize["destinations"] = o.Destinations
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.AgentProtocol) {
		toSerialize["agent_protocol"] = o.AgentProtocol
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	return toSerialize, nil
}

func (o *UpdateRouteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRouteRequest := _UpdateRouteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRouteRequest)

	if err != nil {
		return err
	}

	*o = UpdateRouteRequest(varUpdateRouteRequest)

	return err
}

type NullableUpdateRouteRequest struct {
	value *UpdateRouteRequest
	isSet bool
}

func (v NullableUpdateRouteRequest) Get() *UpdateRouteRequest {
	return v.value
}

func (v *NullableUpdateRouteRequest) Set(val *UpdateRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRouteRequest(val *UpdateRouteRequest) *NullableUpdateRouteRequest {
	return &NullableUpdateRouteRequest{value: val, isSet: true}
}

func (v NullableUpdateRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
